Comment aquire image that occures
Error while installing :
```pyhton
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 683, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 572, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 149, in _eval_xml
    with file_open(node.get('file'), 'rb') as f:
  File "/home/odoo/src/odoo/odoo/tools/misc.py", line 198, in file_open
    path = file_path(name, filter_ext=filter_ext)
  File "/home/odoo/src/odoo/odoo/tools/misc.py", line 179, in file_path
    raise FileNotFoundError("File not found: " + file_path)
FileNotFoundError: File not found: payment_payfip/static/src/img/payfip_icon.png

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1330, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1318, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 486, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 603, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 748, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 814, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 734, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 683, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 696, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/odoo/src/repositories/l10n_france/l10n_fr_payment_payfip/data/payment_acquirer.xml:4, somewhere inside
<record id="payment_acquirer_payfip" model="payment.acquirer">
            <field name="name">PayFIP</field>
            <field name="image_128" type="base64" file="payment_payfip/static/src/img/payfip_icon.png"/>
            <field name="provider">payfip</field>
            <field name="company_id" ref="base.main_company"/>
            <field name="redirect_form_view_id" ref="redirect_form"/>
            <field name="pre_msg">
                &lt;p&gt;You will be redirected to the PayFIP website after clicking on the payment button.&lt;/p&gt;
            </field>
            <field name="payfip_customer_number">dummy</field>
            <field name="payfip_form_action_url">https://www.tipi-client.budget.gouv.fr/tpa/paiementws.web</field>
            <field name="description" type="html">
                <p>PayFIP est un système de paiement en ligne français proposé pa la Direction générale des Finances
                    Publiques. Son but est de faciliter le paiement des services publics locaux.
                </p>
                <ul class="list-inline">
                    <li><i class="fa fa-check"/>eCommerce
                    </li>
                </ul>
            </field>
        </record>
```